name: Vue Simulator Desktop Automated Release Pipeline

on:
  push:
    branches: [ "main" ]
  release:
    types: [created]

env:
  APP_VERSION: $(git describe --tags --abbrev=0 || echo "v1.0.0")

jobs:
  build-tauri:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies (Vue + Tauri CLI)
        run: |
          npm install
          npm install -g @tauri-apps/cli
        working-directory: ./src  

      - name: Build Frontend (Vue)
        run: |
          npm run desktop
        working-directory: ./src  

      - name: Setup Rust
        if: matrix.os != 'windows-latest'
        run: |
          rustup update stable
          rustup default stable

      - name: Cache Rust Dependencies
        uses: Swatinem/rust-cache@v2

      - name: Determine Version
        id: version
        run: echo "VERSION=$(git describe --tags --abbrev=0 || echo 'v1.0.0')" >> $GITHUB_ENV

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        with:
          projectPath: ./src-tauri 
          tagName: "${{ env.VERSION }}"
          releaseName: "Vue Simulator Desktop ${{ env.VERSION }}"
          releaseBody: "Automated release pipeline with automated versioning. See the assets below to download."
          releaseDraft: false
          prerelease: false

      - name: Upload Tauri Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Vue Simulator ${{ env.VERSION }} Build Artifacts (${{ matrix.os }})
          path: |
            src-tauri/target/release/bundle

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: src-tauri/target/release/bundle/**/*
          tag_name: "${{ env.VERSION }}"
          name: "Vue Simulator Desktop ${{ env.VERSION }}"
          body: "Automated release pipeline with automated versioning."
          draft: false
          prerelease: false
